# Generated by Django 5.1.4 on 2024-12-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontent', '0002_alter_article_options_article_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
