# Generated by Django 5.1.4 on 2024-12-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontent', '0005_category_article_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maincontent.category'),
        ),
    ]
