# Generated by Django 5.1.4 on 2024-12-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontent', '0007_alter_article_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='maincontent.tagpost'),
        ),
    ]
