# Generated by Django 5.1.4 on 2025-01-06 07:07

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontent', '0008_tagpost_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-time_create'], 'verbose_name': 'Статьи (Article)', 'verbose_name_plural': 'Статьи (Article)'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории (Category)', 'verbose_name_plural': 'Категории (Category)'},
        ),
        migrations.AlterField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='maincontent.category', verbose_name='CATEGORY'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category'),
        ),
    ]
