# Generated by Django 5.1.4 on 2025-01-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontent', '0010_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
